### ISSUE TITLE
Exception while updating company

### ISSUE THREAD

**Issue by JordenDiEgidio** [janhenkes/teamleader-php-sdk#20]
Hello,

I'm trying to update a company by ID but I keep getting the following error from the Teamleader API:

{"errors":[{"code":404000,"title":"Resource /companies.update/a0f2b5e2-b793-0c74-8b70-b564e1d4d5c8 not found.","status":404}]} {"e":"[object] (Teamleader\\Exceptions\\ApiException(code: 404): Error 404: {\"errors\":[{\"code\":404000,\"title\":\"Resource /companies.update/xxxxxxx not found.\",\"status\":404}]}

I'm able to add a company with this PHP client but updating doesn't seem to work. Below the code I'm using:

```
<?php

$connection = new \Teamleader\Connection();
$connection->setClientId($clientId);
$connection->setClientSecret($clientSecret);

$client = new \Teamleader\Client($connection);

$company = [
    'id' => 'xxxxxxx',
    'name' => 'Customer 1',
    //...
];

$client->company($company)->save();
```

Using findById() I'm able to get the customer using the same ID.

**Comment by janhenkes** [comment]
Hi @JordenDiEgidio ,

Thanks for pointing this out. I think there might be a bug here since the company ID shouldn't be passed in the URL but in the request body (https://developer.teamleader.eu/#/reference/crm/contacts/companies.update). I will create a fix for you.

**Comment by janhenkes** [comment]
Hi @JordenDiEgidio ,

I just created a new version (2.0.0) in which your error should be fixed.
