### ISSUE TITLE
Filtering on an entity does not seem to work

### ISSUE THREAD

**Issue by maxi032** [janhenkes/teamleader-php-sdk#23]
I am trying to use Teamleader\Actions\Attributes\Filter but it does not seem to have any effect on the data I am getting.

For example:

`$companies = $client->company()->get($filter, $page); ` will give me paginated data but it will have no effect on filters

**Comment by maxi032** [comment]
Maybe you could provide a working example?

**Comment by janhenkes** [comment]
@maxi032 , can you give me a full code example of what you are trying to achieve?
