### ISSUE TITLE
Guzzle HTTP version

### ISSUE THREAD

**Issue by idmeneo** [janhenkes/teamleader-php-sdk#45]
Why do you force the 6.0 version of Guzzle HTTP ? This is very restrictive. I use 6.5 and cannot update your package...

**Comment by janhenkes** [comment]
Hi @idmeneo , strange, the package is not fixed to 6.0, actually 6.5.5 is installed. Can you provide the error message?

**Comment by idmeneo** [comment]
Hello @janhenkes sorry for the delay in the response. 
My mistake I use the version 7.2 of Guzzle so I get this error: 

>Problem 1
    - Root composer.json requires janhenkes/teamleader-php-sdk ^2.9 -> satisfiable by janhenkes/teamleader-php-sdk[2.9.0].
    - janhenkes/teamleader-php-sdk 2.9.0 requires guzzlehttp/guzzle ^6.0 -> found guzzlehttp/guzzle[6.0.0, ..., 6.5.x-dev] but it conflicts with your root composer.json require (^7.2).

I tried to downgrade Guzzle HTTP but I got into other problems so it is not the best idea.

The other problem I am facing is that anything I can do, the **Task Title remains empty**. 
Knowing the fact that I want to update your package only for this feature (the title field for "task" was missing before) I'm in a deadend.

Thank you for your help.

**Comment by cschalenborgh** [comment]
This package is currently not compatible with Guzzle 7 it seems.
See https://github.com/janhenkes/teamleader-php-sdk/issues/47 for more details.
