### ISSUE TITLE
Call to undefined function GuzzleHttp\Psr7\rewind_body() 

### ISSUE THREAD

**Issue by cschalenborgh** [janhenkes/teamleader-php-sdk#47]
**Configuration**
guzzlehttp/guzzle: 7.4.1
guzzlehttp/psr7: 2.1.0
PHP version: 7.4

**Description:**
The latest version of Guzzle (7.4.x) isn't supported by this library.
It throws an error on this line: https://github.com/janhenkes/teamleader-php-sdk/blob/master/src/Teamleader/Connection.php#L197
=>
```
"Call to undefined function GuzzleHttp\Psr7\rewind_body()"
```

**Temporary fix:**
Use an older version of Guzzle in your application. 6.5 does the trick here.
```
"guzzlehttp/guzzle": "^6.5",
```

**Comment by janhenkes** [comment]
@cschalenborgh Thanks for reporting this issue, it should be solved!
