### ISSUE TITLE
Can the storage path set via a variable?

### ISSUE THREAD

**Issue by maxi032** [janhenkes/teamleader-php-sdk#52]
Thank you for the package. Very useful
I was wondering if it would be possible to have the storage of the tokens set via a variable because I don't want to store them in /tmp

Thank you

**Comment by janhenkes** [comment]
Hi @maxi032 ,

You can implement your own token storage by creating a class which implements the `CacheHandlerInterface` class.
The default `DefaultCacheHandler` is just an example provided in this package. You are free to save your tokens where you like (database, file storage, etc).

You can use your custom cache handler as follows:

```
$cacheHandler = new MyCustomCacheHandler();
$connection = new \Teamleader\Connection($cacheHandler); 
``` 

I hope this helps.
