### ISSUE TITLE
Upgrade to latest  Teamleader version ( min version 2022-09-15)

### ISSUE THREAD

**Issue by langeuh** [janhenkes/teamleader-php-sdk#57]
due to the `'X-Api-Version' => '2021-09-01'`header for every request, we get following error:

`Can not downgrade to a lower API version than 2022-09-15`

https://developer.focus.teamleader.eu/#/introduction/changes-&-upgrades/upgrading-your-api-version

can these changes be implemented and the header upgraded or make the 'X-Api-Version' header optional?
currently unable to use this package

I'd prefer getting rid of the header, as it might break any time whenever teamleader decides to change the 'minimum date'. Breaking changes only affect 1% of the API requests.

**Comment by dtrdewaele** [comment]
Hi,
Also fixed this in fork on https://github.com/dtrdewaele/teamleader-php-sdk
